// Vier weekmenu's die rouleren, met recept per dag voor 1 persoon.
// Ingrediënt: [hoeveelheid, naam, basis]. basis = 1: staat op de vaste boodschappenlijst of in je kast (zout, olie, kruiden, ui).
// Week 1 = de week van 14 september 2026. Dezelfde rotatie gebruikt ../AH Boodschappen/weekmenus.json.
window.VOLHOUDEN_RECEPTEN = {
  start: "2026-09-14",
  menus: [
    {naam: "Menu 1", dagen: [
      {dag: "Ma", gerecht: "Linzencurry met rijst en spinazie", kosten: "€ 2", tijd: 25,
       ing: [["75 g","rijst",1],["100 g","rode linzen"],["200 ml","kokosmelk"],["100 g","diepvriesspinazie"],["1","ui",1],["1 teen","knoflook",1],["1 el","kerriepoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de rijst volgens de verpakking.","Snipper de ui en de knoflook. Bak ze 3 minuten in de olie in een pan.","Roer de kerrie erdoor en bak 30 seconden mee.","Voeg de linzen, de kokosmelk en 150 ml water toe. Laat 15 minuten zachtjes koken, roer af en toe.","Roer de spinazie erdoor en warm 3 minuten mee. Breng op smaak met zout en peper.","Serveer over de rijst."]},
      {dag: "Di", gerecht: "Volkorenpasta met tonijn, tomaat en ui", kosten: "€ 2,50", tijd: 20,
       ing: [["80 g","volkorenpasta",1],["1 blikje","tonijn in blik"],["200 g","tomatenblokjes"],["1","ui",1],["1 teen","knoflook",1],["1 el","olijfolie",1],["1 tl","paprikapoeder",1],["","zout en peper",1]],
       stappen: ["Kook de pasta volgens de verpakking.","Snipper de ui en de knoflook en bak ze 3 minuten in de olie.","Voeg de tomatenblokjes en het paprikapoeder toe. Laat 8 minuten pruttelen.","Laat de tonijn uitlekken en roer hem door de saus. Warm 2 minuten mee.","Meng de pasta door de saus. Zout en peper naar smaak."]},
      {dag: "Wo", gerecht: "Aardappelen, sperziebonen en een gebakken ei", kosten: "€ 2", tijd: 25,
       ing: [["300 g","aardappelen",1],["200 g","sperziebonen"],["2","eieren",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Schil de aardappelen, snijd ze in stukken en kook ze in 15 tot 20 minuten gaar.","Maak de sperziebonen schoon en kook ze 8 minuten in water met zout.","Bak de eieren in de olie tot het eiwit stevig is.","Giet alles af en zet het op een bord. Zout en peper erover."]},
      {dag: "Do", gerecht: "Chili met bonen, mais en rijst", kosten: "€ 2", tijd: 25,
       ing: [["75 g","rijst",1],["1 blik","kidneybonen"],["1 klein blik","mais in blik"],["1","paprika"],["200 g","tomatenblokjes"],["1","ui",1],["1 teen","knoflook",1],["1 tl","komijn",1],["1 tl","paprikapoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de rijst volgens de verpakking.","Snijd de ui, de knoflook en de paprika klein. Bak ze 5 minuten in de olie.","Voeg komijn en paprikapoeder toe en bak 30 seconden mee.","Spoel de bonen en de mais af en doe ze met de tomatenblokjes in de pan. Laat 10 minuten pruttelen.","Breng op smaak met zout en peper en serveer met de rijst. De helft is morgen een prima lunch."]},
      {dag: "Vr", gerecht: "Omelet met champignons en paprika, volkorenbrood", kosten: "€ 2", tijd: 15,
       ing: [["3","eieren",1],["125 g","champignons"],["1","paprika"],["2 sneden","volkorenbrood",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Snijd de champignons en de paprika in stukjes. Bak ze 5 minuten in de olie.","Klop de eieren los met zout en peper en giet ze over de groente.","Laat op laag vuur 5 minuten stollen. Vouw de omelet dubbel.","Eet met het brood erbij."]},
      {dag: "Za", gerecht: "Wokgroente met tofu en noedels", kosten: "€ 3", tijd: 20,
       ing: [["75 g","noedels"],["150 g","tofu"],["250 g","wokgroente"],["2 el","sojasaus"],["1 teen","knoflook",1],["1 el","olijfolie",1]],
       stappen: ["Dep de tofu droog en snijd hem in blokjes. Bak ze 6 minuten in hete olie tot ze goudbruin zijn.","Kook ondertussen de noedels volgens de verpakking.","Voeg knoflook en wokgroente bij de tofu en wok 4 minuten.","Roer de noedels en de sojasaus erdoor en warm even door."]},
      {dag: "Zo", gerecht: "Ovenschotel met aardappel, prei en kaas", kosten: "€ 3", tijd: 45,
       ing: [["350 g","aardappelen",1],["1","prei"],["50 g","geraspte kaas"],["100 ml","melk",1],["1","ei",1],["1 el","olijfolie",1],["","zout, peper en nootmuskaat",1]],
       stappen: ["Verwarm de oven voor op 200 graden.","Schil de aardappelen, snijd ze in dunne plakken en kook ze 8 minuten voor.","Snijd de prei in ringen en bak hem 5 minuten in de olie.","Doe aardappel en prei in een ovenschaal. Klop ei en melk los met zout, peper en nootmuskaat en giet het erover. Strooi de kaas erop.","Bak 25 minuten tot de bovenkant goudbruin is."]}
    ]},
    {naam: "Menu 2", dagen: [
      {dag: "Ma", gerecht: "Kikkererwtencurry met rijst", kosten: "€ 2", tijd: 25,
       ing: [["75 g","rijst",1],["1 blik","kikkererwten"],["200 ml","kokosmelk"],["200 g","tomatenblokjes"],["1","ui",1],["1 teen","knoflook",1],["1 el","kerriepoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de rijst volgens de verpakking.","Snipper ui en knoflook en bak ze 3 minuten in de olie. Roer de kerrie erdoor.","Voeg tomatenblokjes en kokosmelk toe en laat 5 minuten koken.","Spoel de kikkererwten af, roer ze erdoor en laat 10 minuten pruttelen.","Zout en peper naar smaak. Serveer met de rijst."]},
      {dag: "Di", gerecht: "Bloemkool, aardappelpuree en een gehaktbal", kosten: "€ 3", tijd: 35,
       ing: [["300 g","aardappelen",1],["half","bloemkool"],["125 g","gehakt"],["1","ei",1],["2 el","paneermeel of havermout",1],["100 ml","melk",1],["1 el","olijfolie",1],["","zout, peper en nootmuskaat",1]],
       stappen: ["Meng het gehakt met een half ei, het paneermeel, zout en peper. Draai er een bal van.","Bak de bal in de olie rondom bruin en laat hem op laag vuur 15 minuten garen met de deksel erop.","Kook de aardappelen 20 minuten. Kook de bloemkoolroosjes de laatste 10 minuten mee in een andere pan.","Stamp de aardappelen met de melk en nootmuskaat tot puree.","Serveer met het bakvet van de bal als jus."]},
      {dag: "Wo", gerecht: "Pasta met broccoli, knoflook en kip", kosten: "€ 3", tijd: 20,
       ing: [["80 g","volkorenpasta",1],["half","broccoli"],["125 g","kipfilet"],["2 tenen","knoflook",1],["1 el","olijfolie",1],["","zout, peper en chilivlokken",1]],
       stappen: ["Kook de pasta. Kook de broccoliroosjes de laatste 5 minuten mee.","Snijd de kip in reepjes en bak ze 6 minuten in de olie met zout en peper.","Voeg de gesneden knoflook toe en bak 1 minuut mee.","Giet de pasta en broccoli af, bewaar een scheutje kookvocht, en meng alles door de kip. Chilivlokken erover als je wilt."]},
      {dag: "Do", gerecht: "Tomatensoep met linzen en volkorenbrood", kosten: "€ 2", tijd: 30,
       ing: [["400 g","tomatenblokjes"],["75 g","rode linzen"],["2","wortelen"],["1","ui",1],["1 teen","knoflook",1],["1","bouillonblokje",1],["2 sneden","volkorenbrood",1],["1 el","olijfolie",1],["","peper",1]],
       stappen: ["Snipper ui en knoflook, snijd de wortel in blokjes. Bak alles 5 minuten in de olie.","Voeg tomatenblokjes, linzen, het bouillonblokje en 500 ml water toe.","Laat 20 minuten zachtjes koken tot de linzen zacht zijn.","Pureer met een staafmixer of laat grof. Peper naar smaak, brood erbij."]},
      {dag: "Vr", gerecht: "Wraps met zwarte bonen, mais en sla", kosten: "€ 2,50", tijd: 15,
       ing: [["2","volkoren wraps"],["1 blik","zwarte bonen"],["1 klein blik","mais in blik"],["handvol","sla"],["1 tl","komijn",1],["1 tl","paprikapoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Spoel de bonen en de mais af. Verwarm ze 5 minuten in een pan met de olie, komijn, paprikapoeder, zout en peper. Prak de bonen een beetje.","Warm de wraps 20 seconden in een droge koekenpan.","Vul de wraps met het bonenmengsel en de sla en rol ze op."]},
      {dag: "Za", gerecht: "Gebakken rijst met ei, doperwten en wortel", kosten: "€ 2", tijd: 20,
       ing: [["75 g","rijst",1],["2","eieren",1],["100 g","diepvries doperwten"],["1","wortelen"],["1","ui",1],["2 el","sojasaus"],["1 el","olijfolie",1]],
       stappen: ["Kook de rijst en laat hem uitdampen. Rijst van gisteren is nog beter.","Snipper de ui en snijd de wortel in kleine blokjes. Bak ze 5 minuten in de olie.","Schuif de groente opzij, breek de eieren in de pan en roer ze los tot ze gestold zijn.","Voeg rijst, doperwten en sojasaus toe en bak 4 minuten op hoog vuur."]},
      {dag: "Zo", gerecht: "Stamppot boerenkool met rookworst", kosten: "€ 3", tijd: 30,
       ing: [["350 g","aardappelen",1],["200 g","boerenkool"],["1","rookworst"],["100 ml","melk",1],["1 el","olijfolie of boter",1],["1 tl","mosterd",1],["","zout en peper",1]],
       stappen: ["Schil de aardappelen en kook ze 20 minuten. Leg de boerenkool er de laatste 10 minuten bovenop.","Warm de rookworst volgens de verpakking.","Giet af, voeg melk, olie en mosterd toe en stamp tot een grove stamppot.","Zout en peper naar smaak, worst erbij."]}
    ]},
    {naam: "Menu 3", dagen: [
      {dag: "Ma", gerecht: "Dahl van rode linzen met rijst", kosten: "€ 2", tijd: 25,
       ing: [["75 g","rijst",1],["100 g","rode linzen"],["200 ml","kokosmelk"],["100 g","diepvriesspinazie"],["1","ui",1],["1 teen","knoflook",1],["1 tl","komijn",1],["1 tl","kerriepoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de rijst volgens de verpakking.","Bak ui en knoflook 3 minuten in de olie. Voeg komijn en kerrie toe.","Voeg linzen, kokosmelk en 200 ml water toe. Laat 15 minuten koken tot het dik is.","Roer de spinazie erdoor, warm 3 minuten mee. Zout en peper naar smaak."]},
      {dag: "Di", gerecht: "Pasta pesto met sperziebonen en kip", kosten: "€ 3", tijd: 20,
       ing: [["80 g","volkorenpasta",1],["2 el","pesto"],["150 g","sperziebonen"],["125 g","kipfilet"],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de pasta. Kook de sperziebonen (in stukjes) de laatste 6 minuten mee.","Snijd de kip in reepjes en bak ze 6 minuten in de olie met zout en peper.","Giet de pasta af en meng alles met de pesto."]},
      {dag: "Wo", gerecht: "Aardappelen, spruitjes en een ei", kosten: "€ 2", tijd: 25,
       ing: [["300 g","aardappelen",1],["200 g","spruitjes"],["2","eieren",1],["1 el","olijfolie",1],["","zout, peper en nootmuskaat",1]],
       stappen: ["Kook de aardappelen 20 minuten.","Maak de spruitjes schoon, halveer ze en kook ze 10 minuten. Of bak ze 12 minuten in de olie, dat is lekkerder.","Bak de eieren.","Alles op een bord met zout, peper en wat nootmuskaat over de spruitjes."]},
      {dag: "Do", gerecht: "Bonenstoof met paprika en rijst", kosten: "€ 2", tijd: 25,
       ing: [["75 g","rijst",1],["1 blik","bruine bonen"],["1","paprika"],["200 g","tomatenblokjes"],["1","ui",1],["1 teen","knoflook",1],["1 tl","paprikapoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de rijst.","Snijd ui, knoflook en paprika en bak ze 5 minuten in de olie. Paprikapoeder erbij.","Voeg de bonen met een deel van het vocht en de tomatenblokjes toe. Laat 10 minuten pruttelen.","Zout en peper naar smaak, serveer met de rijst."]},
      {dag: "Vr", gerecht: "Shakshuka: eieren in tomatensaus, met brood", kosten: "€ 2,50", tijd: 20,
       ing: [["2","eieren",1],["400 g","tomatenblokjes"],["1","paprika"],["1","ui",1],["1 teen","knoflook",1],["1 tl","komijn",1],["1 tl","paprikapoeder",1],["2 sneden","volkorenbrood",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Snijd ui, knoflook en paprika en bak ze 5 minuten in de olie.","Voeg komijn, paprikapoeder en de tomatenblokjes toe. Laat 8 minuten inkoken.","Maak twee kuiltjes in de saus en breek daar de eieren in. Deksel erop en 6 minuten laten stollen.","Zout en peper, brood erbij om te dippen."]},
      {dag: "Za", gerecht: "Noedels met kip, wokgroente en pinda", kosten: "€ 3", tijd: 20,
       ing: [["75 g","noedels"],["125 g","kipfilet"],["250 g","wokgroente"],["1 el","pindakaas",1],["2 el","sojasaus"],["1 teen","knoflook",1],["1 el","olijfolie",1]],
       stappen: ["Kook de noedels volgens de verpakking.","Bak de kip in reepjes 6 minuten in de olie. Voeg knoflook en wokgroente toe en wok 4 minuten.","Roer pindakaas, sojasaus en 3 el water tot een saus en giet die erbij.","Meng de noedels erdoor."]},
      {dag: "Zo", gerecht: "Ovenschotel zoete aardappel, kikkererwt en feta", kosten: "€ 3,50", tijd: 45,
       ing: [["1 grote","zoete aardappel"],["1 blik","kikkererwten"],["half","courgette"],["50 g","feta"],["1","ui",1],["1 tl","paprikapoeder",1],["1 tl","komijn",1],["2 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Verwarm de oven voor op 200 graden.","Snijd de zoete aardappel, courgette en ui in stukken. Spoel de kikkererwten af.","Meng alles op een bakplaat met olie, paprikapoeder, komijn, zout en peper.","Rooster 30 minuten. Verkruimel de feta erover en zet nog 5 minuten terug."]}
    ]},
    {naam: "Menu 4", dagen: [
      {dag: "Ma", gerecht: "Couscous met geroosterde groente en kikkererwten", kosten: "€ 2,50", tijd: 35,
       ing: [["75 g","couscous"],["half","courgette"],["1","paprika"],["1 blik","kikkererwten"],["1","ui",1],["1 tl","komijn",1],["1 tl","paprikapoeder",1],["2 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Verwarm de oven voor op 200 graden.","Snijd courgette, paprika en ui in stukken. Meng met de afgespoelde kikkererwten, olie en kruiden op een bakplaat. Rooster 25 minuten.","Giet 100 ml kokend water op de couscous, deksel erop, 5 minuten laten staan en losroeren met een vork.","Schep de groente over de couscous."]},
      {dag: "Di", gerecht: "Macaroni met tomatensaus, gehakt en kaas", kosten: "€ 3", tijd: 25,
       ing: [["80 g","macaroni of volkorenpasta",1],["125 g","gehakt"],["200 g","tomatenblokjes"],["50 g","geraspte kaas"],["1","ui",1],["1 teen","knoflook",1],["1 tl","paprikapoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de pasta.","Bak het gehakt rul in de olie. Voeg ui en knoflook toe en bak 3 minuten mee.","Voeg tomatenblokjes en paprikapoeder toe en laat 8 minuten pruttelen.","Meng de pasta erdoor, kaas erover."]},
      {dag: "Wo", gerecht: "Hutspot met wortel, ui en een gehaktbal", kosten: "€ 2,50", tijd: 35,
       ing: [["300 g","aardappelen",1],["3","wortelen"],["2","uien",1],["125 g","gehakt"],["1","ei",1],["100 ml","melk",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Meng het gehakt met een half ei, zout en peper en draai er een bal van. Bak hem bruin en laat hem 15 minuten garen onder een deksel.","Kook de aardappelen, de wortel in stukken en de ui in parten samen 20 minuten.","Giet af, voeg de melk toe en stamp grof. Zout en peper.","Serveer met de bal en het bakvet."]},
      {dag: "Do", gerecht: "Linzensoep met prei en volkorenbrood", kosten: "€ 2", tijd: 30,
       ing: [["100 g","rode linzen"],["1","prei"],["2","wortelen"],["1","ui",1],["1","bouillonblokje",1],["1 tl","komijn",1],["2 sneden","volkorenbrood",1],["1 el","olijfolie",1],["","peper",1]],
       stappen: ["Snijd prei, wortel en ui klein en bak ze 5 minuten in de olie.","Voeg linzen, komijn, bouillonblokje en 600 ml water toe.","Laat 20 minuten koken tot de linzen uit elkaar vallen.","Peper naar smaak, brood erbij."]},
      {dag: "Vr", gerecht: "Tosti's met kaas en tomaat, salade erbij", kosten: "€ 2", tijd: 15,
       ing: [["4 sneden","volkorenbrood",1],["60 g","kaas"],["1","tomaat"],["handvol","sla"],["kwart","komkommer"],["1 tl","olijfolie",1],["","peper",1]],
       stappen: ["Beleg twee sneden brood met kaas en plakjes tomaat, leg de andere sneden erop.","Bak de tosti's in een koekenpan of tosti-ijzer tot de kaas smelt.","Snijd de komkommer en meng met de sla en de olie. Peper erover."]},
      {dag: "Za", gerecht: "Kip-kerrie met rijst en doperwten", kosten: "€ 3", tijd: 25,
       ing: [["75 g","rijst",1],["125 g","kipfilet"],["100 g","diepvries doperwten"],["1","ui",1],["1 el","kerriepoeder",1],["100 ml","melk",1],["1 el","bloem",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Kook de rijst. Kook de doperwten de laatste 4 minuten mee.","Bak de kip in blokjes 5 minuten in de olie. Voeg de ui toe en bak 3 minuten mee.","Strooi kerrie en bloem erover, roer 1 minuut en giet de melk en 100 ml water erbij. Roer tot een gebonden saus.","Zout en peper naar smaak, serveer met de rijst."]},
      {dag: "Zo", gerecht: "Gevulde paprika's met rijst en bonen", kosten: "€ 2,50", tijd: 45,
       ing: [["2","paprika"],["50 g","rijst",1],["1 klein blik","bruine bonen"],["50 g","geraspte kaas"],["1","ui",1],["1 tl","komijn",1],["1 tl","paprikapoeder",1],["1 el","olijfolie",1],["","zout en peper",1]],
       stappen: ["Verwarm de oven voor op 200 graden. Kook de rijst.","Bak de ui 3 minuten in de olie. Meng met de rijst, de afgespoelde bonen, komijn, paprikapoeder, zout en peper.","Halveer de paprika's, haal de zaadjes eruit en vul ze met het mengsel. Kaas erop.","Bak 25 minuten in de oven."]}
    ]}
  ]
};
